=head1 SYNOPSIS

B<convertgls2bib> [I<option>]+ I<auxfile>

=head1 DESCRIPTION

Converts a B<.tex> file containing glossary definitions using
commands like C<\newglossaryentry> and C<\newacronym> to 
a B<.bib> file in the format required for B<bib2gls>.

=head1 OPTIONS

=over 4

=item B<--help> or B<-h>

Display help message and exit.

=item B<--version> or B<-v>

Display version information and exit.

=item B<--silent>

Suppress all messages except for errors.

=item B<--verbose>

Display messages.

=item B<--debug>

Display debugging messages.

=item B<--texenc> I<name>

Set the character encoding to I<name> for the input B<.tex> files.

=item B<--bibenc> I<name>

Set the character encoding to I<name> for the output B<.bib> files.

=item B<--ignore-sort>

Ignore the B<sort> field (default).

=item B<--no-ignore-sort>

Don't ignore the B<sort> field.

=item B<--ignore-type>

Omit the B<type> field. Default if B<--split-on-type>.

=item B<--no-ignore-type>

Don't omit the B<type> field. Default unless B<--split-on-type>.

=item B<--split-on-type> or B<-t>

Split the entries into separate files according to the B<type> field.
This option automatically implements B<--ignore-type> and
B<--no-overwrite>.

=item B<--no-split-on-type>

Don't split the entries into separate files according to the B<type>
field (default).

=item B<--ignore-category>

Omit the B<category> field. Default if B<--split-on-category>.

=item B<--no-ignore-category>

Don't omit the B<category> field. Default unless B<--split-on-category>.

=item B<--split-on-category> or B<-t>

Split the entries into separate files according to the B<category> field.
This option automatically implements B<--ignore-category> and
B<--no-overwrite>.

=item B<--no-split-on-category>

Don't split the entries into separate files according to the B<category>
field (default).

=item B<--ignore-fields> I<list> or B<-f> I<list>

Ignore all the fields in the comma-separated I<list>. If the
list includes B<sort>, B<type> or B<category> it will automatically
implement the corresponding B<--ignore-sort>, B<--ignore-type> or
B<--ignore--category> option.

This option isn't cumulative. An empty list will clear a previously
set list but won't undo the sort, type or category ignore options.

=item B<--overwrite>

Overwrite existing .bib files. Default unless B<--split-on-type>
used.

=item B<--no-overwrite>

Don't overwrite existing .bib files. Default if B<--split-on-type>
used.

=item B<--index-conversion> or B<-i>

Any entries that would normally be converted to C<@entry> that don't
have a description or just have the description set to
C<\nopostdesc> or C<\glsxtrnopostpunc> will be converted to C<@index>
and the B<description> field will be omitted.

=item B<--no-index-conversion> 

Don't use C<@index> instead of C<@entry> if the description is empty or
just C<\nopostdesc> or C<\glsxtrnopostpunc> (default).

=item B<--absorb-see> 

Absorb C<\glssee> and C<\glsxtrindexseealso> into the data (default).

=item B<--no-absorb-see> 

Don't absorb C<\glssee> and C<\glsxtrindexseealso> into the data.

=item B<--preamble-only> or B<-p>

Only parse the document preamble.

=item B<--no-preamble-only>

Parse the entire document (default).

=item B<--space-sub> I<value> or B<-s> I<value>

Substitute spaces in labels with I<value>.

=item B<--locale> I<lang tag>

Use the language resource files associated with the given language
tag I<lang tag>. If there isn't an appropriate file, the B<en>
(English) file will be used.

=back

=head1 REQUIRES

Java 8 and a TeX distribution.

=head1 LICENSE

License GPLv3+: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

=head1 RECOMMENDED READING

The bib2gls manual:

        texdoc bib2gls

The glossaries-extra manual:

        texdoc glossaries-extra

The glossaries manual:

        texdoc glossaries

=head1 AUTHOR

Nicola L. C. Talbot,
L<http://www.dickimaw-books.com/>

=cut

